#!/bin/bash

set -e

OTP_META_FILE=$ERL_TOP/${TRAVIS_TAG}-collection.txt
OTP_FILE=$ERL_TOP/${TRAVIS_TAG}-collection.tar.gz

REPOSITORIES="otp,$TRAVIS_TAG percept,.* corba,.*"

mkdir deploy

for repo in $REPOSITORIES; do
    OLD_IFS=$IFS
    IFS=','
    set -- $repo
    IFS=$OLD_IFS
    cd $ERL_TOP/deploy/
    git clone https://github.com/erlang/$1 $1
    cd $1
    echo $1 $2
    TAG=`git tag -l | grep -P "$2" | sort -V | tail -1`
    git checkout $TAG
    SHA=`git rev-parse --verify HEAD`
    rm -rf .git
    echo "$1 $TAG $SHA" >> $OTP_META_FILE
done

cd $ERL_TOP/deploy/
tar czf $OTP_FILE *
