#!/bin/bash
set -ev

if [ "${1}" = "smoke" ]; then
    CMD="erl -noshell -s ts install -s ts smoke_test batch -s init stop"
elif [ "${1}" = "all" ]; then
    CMD="erl -noshell -s ts install -s ts run all_tests -s init stop"
else
    CMD="erl -noshell -s ts install -s ts run ${1} -s init stop"
fi

if [ -d $ERL_TOP/release/tests/test_server ]; then
    cd $ERL_TOP/release/tests/test_server
elif [ -d test_server ]; then
    cd test_server
else
    echo "Could not find tests"
    exit 1;
fi

${CMD}

if grep -q '=failed *[1-9]' ct_run.test_server@*/*/run.*/suite.log; then
    echo "One or more tests failed."
    exit 1
fi

rm -rf ct_run.test_server@*
