ARG BASE=otp-ubuntu-64
FROM $BASE as BASE

RUN apt-get update && apt-get --fix-missing -y install postgresql odbc-postgresql tzdata ssh \
        openssh-server groff-base sudo apache2 bind9 expect vsftpd

ARG gid=10
ARG uid=421

RUN echo "Europe/Stockholm" > /etc/timezone && \
        ln -snf /usr/share/zoneinfo/$(cat /etc/timezone) /etc/localtime && \
        useradd -rm -d /home/otptest -s /bin/sh -g ${gid} -G ${gid},sudo -u ${uid} otptest && \
        echo "otptest ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/otptest

RUN chown -R otptest:uucp /buildroot/tests
ENV PATH=/otp/bin:$PATH

USER postgres

RUN service postgresql start && \
        psql -c "CREATE USER odbctest WITH SUPERUSER PASSWORD 'odbctest';" && \
        createdb -O odbctest odbctest && \
        service postgresql stop

COPY --chown=root:uucp odbc.ini /etc/
COPY --chown=root:uucp odbcinst.ini /etc/

USER otptest

RUN echo "mkdir -p -m0755 /var/run/sshd" > /home/otptest/init.sh && \
        echo "/usr/sbin/sshd" >> /home/otptest/init.sh && \
        echo "service postgresql start" >> /home/otptest/init.sh && \
        chmod +x /home/otptest/init.sh

WORKDIR /buildroot/tests/test_server

CMD ["sudo /home/otptest/init.sh && erl -noinput -s ts install -s init stop && erl -noinput -s ts run odbc -s init stop && sudo cp -r * /buildroot/tests/logs"]
