{global,_} = Code.eval_file Path.join(System.get_env("ERL_TOP"),"ex_doc.exs");
deps = Path.wildcard("lib/*/ebin") |> Enum.map(
  fn path ->
    app = Path.split(path) |> Enum.at(1);
    {String.to_atom(app), Path.join(["..",app])}
  end);
Keyword.merge(global,
  [
    extras:
    ["system/doc/README.md",
     "system/doc/installation_guide/installation_guide.md",
     "system/doc/installation_guide/install-binary.md",
     "system/doc/installation_guide/install.md",
     "system/doc/installation_guide/install-cross.md",
     "system/doc/installation_guide/install-win32.md",
     "system/doc/installation_guide/otp-patch-apply.md",
     "system/doc/system_principles/system_principles.md",
     "system/doc/system_principles/error_logging.md",
     "system/doc/system_principles/create_target.md",
     "system/doc/system_principles/upgrade.md",
     "system/doc/system_principles/versions.md",
     "system/doc/system_principles/misc.md",
     "system/doc/embedded/embedded.md",
     "system/doc/embedded/embedded_solaris.md",
     "system/doc/embedded/embedded_nt.md",
     "system/doc/getting_started/getting_started.md",
     "system/doc/getting_started/seq_prog.md",
     "system/doc/getting_started/conc_prog.md",
     "system/doc/getting_started/robustness.md",
     "system/doc/getting_started/records_macros.md",
     "system/doc/reference_manual/reference_manual.md",
     "system/doc/reference_manual/character_set.md",
     "system/doc/reference_manual/data_types.md",
     "system/doc/reference_manual/patterns.md",
     "system/doc/reference_manual/modules.md",
     "system/doc/reference_manual/documentation.md",
     "system/doc/reference_manual/ref_man_functions.md",
     "system/doc/reference_manual/typespec.md",
     "system/doc/reference_manual/opaques.md",
     "system/doc/reference_manual/expressions.md",
     "system/doc/reference_manual/macros.md",
     "system/doc/reference_manual/ref_man_records.md",
     "system/doc/reference_manual/errors.md",
     "system/doc/reference_manual/features.md",
     "system/doc/reference_manual/ref_man_processes.md",
     "system/doc/reference_manual/distributed.md",
     "system/doc/reference_manual/code_loading.md",
     "system/doc/reference_manual/ports.md",
     "system/doc/programming_examples/programming_examples.md",
     "system/doc/programming_examples/prog_ex_records.md",
     "system/doc/programming_examples/funs.md",
     "system/doc/programming_examples/list_comprehensions.md",
     "system/doc/programming_examples/bit_syntax.md",
     "system/doc/efficiency_guide/efficiency_guide.md",
     "system/doc/efficiency_guide/myths.md",
     "system/doc/efficiency_guide/commoncaveats.md",
     "system/doc/efficiency_guide/binaryhandling.md",
     "system/doc/efficiency_guide/maps.md",
     "system/doc/efficiency_guide/listhandling.md",
     "system/doc/efficiency_guide/eff_guide_functions.md",
     "system/doc/efficiency_guide/tablesdatabases.md",
     "system/doc/efficiency_guide/eff_guide_processes.md",
     "system/doc/efficiency_guide/drivers.md",
     "system/doc/efficiency_guide/advanced.md",
     "system/doc/efficiency_guide/profiling.md",
     "system/doc/efficiency_guide/retired_myths.md",
     "system/doc/tutorial/tutorial.md",
     "system/doc/tutorial/overview.md",
     "system/doc/tutorial/example.md",
     "system/doc/tutorial/c_port.md",
     "system/doc/tutorial/erl_interface.md",
     "system/doc/tutorial/c_portdriver.md",
     "system/doc/tutorial/cnode.md",
     "system/doc/tutorial/nif.md",
     "system/doc/tutorial/debugging.md",
     "system/doc/design_principles/design_principles.md",
     "system/doc/design_principles/gen_server_concepts.md",
     "system/doc/design_principles/statem.md",
     "system/doc/design_principles/events.md",
     "system/doc/design_principles/sup_princ.md",
     "system/doc/design_principles/spec_proc.md",
     "system/doc/design_principles/applications.md",
     "system/doc/design_principles/included_applications.md",
     "system/doc/design_principles/distributed_applications.md",
     "system/doc/design_principles/release_structure.md",
     "system/doc/design_principles/release_handling.md",
     "system/doc/design_principles/appup_cookbook.md",
     "system/doc/oam/oam.md"
    ],
    main: "readme",
    api_reference: false,
    assets: "system/doc/assets/",
    groups_for_extras: [
      "Installation Guide": ~r/installation_guide/,
      "Getting Started With Erlang": ~r/getting_started/,
      "System Principles": ~r/system_principles/,
      "OTP Design Principles": ~r/design_principles/,
      "Programming Examples": ~r/programming_examples/,
      "Erlang Reference Manual": ~r/reference_manual/,
      "Efficiency Guide": ~r/efficiency_guide/,
      "Interoperability Tutorial": ~r/tutorial/,
      "OAM Principles": ~r/oam/,
      "Embedded Systems User's Guide": ~r/embedded/,
    ]
  ])
